import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/components/Providers'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>

      <html lang="tr" className='text-neutral-900 dark:text-neutral-100 dark:bg-slate-800 bg-neutral-200'>
        <body className={`${inter.className} `}>
          <Providers>
            <div className='  antialiased min-h-screen'>
              <Navbar />
              {children}
            </div>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
