import "@/styles/globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"

import Navbar from "@/components/Navbar"
import Providers from "@/components/Providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html
        lang="tr"
        className="bg-neutral-200 text-neutral-900 dark:bg-slate-800 dark:text-neutral-100"
      >
        <body className={`${inter.className} `}>
          <Providers>
            <div className="  min-h-screen antialiased">
              <Navbar />
              {children}
            </div>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
